spring.application.name=UserThreadJDBC
spring.datasource.url=mysql://root:eebBYBTBJNqUvIfIVFTLNchUMDcHZbkb@interchange.proxy.rlwy.net:26327/railway
spring.datasource.username=root
spring.datasource.password=eebBYBTBJNqUvIfIVFTLNchUMDcHZbkb

# MySQL Driver
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.sql.init.mode=always

# JPA / Hibernate Settings
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect

# Optional (better formatting)
spring.jpa.properties.hibernate.format_sql=true

# Fix port issue


server.port=8080
#spring.datasource.url=jdbc:mysql://${MYSQLHOST}:${MYSQLPORT}/${MYSQLDATABASE}
#spring.datasource.username=${MYSQLUSER}
#spring.datasource.password=${MYSQLPASSWORD}
